### PR TITLE
Fix resizing of maximized applications.

### LINKED ISSUE #29: Can't resize maximized applications
Some maximized applications can't be resized. 

I could observe this problem mainly with Electron-based applications: VS Code, GitKraken, Postman etc. 
Other notable applications, that exhibit the same problem are Opera and Spotify.
"Native" applications work fine, when maximized. For example Windows Explorer, Task Manager, Photos app.

All of the mentioned applications work as intended, if they are not maximized.

### PR DESCRIPTION
**Pull request by DiXN**
This uses `ShowWindow` with `SW_RESTORE` as suggested in #29.

Closes #29.

### CODE REVIEW

**Comment by tarkah** [comment]
Can you remove the last commit since you opened a separate PR for it?

**Comment by DiXN** [comment]
Forgot to push the commit in a new branch first. Should work now.

**Comment by tarkah** [comment]
Perfect, thanks

**Comment by tarkah** [comment]
@DiXN I just tested this out, and the window wasn't resizing to the correct dimensions (I am using 10px margins). I moved the Restore function to occur before I calculate the transparent border adjustment, which appeared to be the cause. Everything resizes correctly now.

**Pull request merged**
